#################
### AUTOSTART ###
#################

# Status bar & wallpaper
exec-once = waybar &
exec-once = hyprpaper
exec-once = hypridle

# Cursor & icon theme (for GTK/XWayland apps)
exec-once = gsettings set org.gnome.desktop.interface cursor-theme Material Light Cursors
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
exec-once = gsettings set org.gnome.desktop.interface icon-theme Zafiro-Nord-Black-Blue

# Authentication & secrets
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets
