wallpaper {
 monitor = eDP-1
 path = /home/yuri/dotfiles/hypr/.config/hypr/hyprpaper-wp/frie.png
 fit_mode = cover
}

wallpaper {
 monitor = HDMI-A-1
 path = /home/yuri/dotfiles/hypr/.config/hypr/hyprpaper-wp/frie.png
 fit_mode = cover
}

splash = false
