#############
### INPUT ###
#############

input {
    kb_layout  = us
    kb_variant =
    kb_model   =
    kb_options =
    kb_rules   =

    follow_mouse = 1
    sensitivity  = 0.45  # -1.0 to 1.0, 0 = no modification

    touchpad {
        natural_scroll = true
    }
}

gestures {
    # workspace_swipe = false
}

# Per-device configs
device {
    name        = epic-mouse-v1
    sensitivity = -0.5
}

device {
    name        = tpps/2-elan-trackpoint
    sensitivity = -0.5  # Disable TrackPoint (buttons handled by touchpad device)
}

# mpv color management fixes
render:cm_fs_passthrough = 2
render:send_content_type = 0
