##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps
# windowrule = suppressevent maximize, class:.*

# XWayland drag fix
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# feh (image viewer) — floating
# windowrule = max_size 1200 800, match:class ^(feh)$
windowrule = float on, match:class ^(feh)$

# impala — floating + centered
windowrule = float on,     match:title ^(impala)$
windowrule = size 900 600, match:title ^(impala)$
windowrule = center on,    match:title ^(impala)$

# bluetuith — floating + centered
windowrule = float on,     match:title ^(bluetuith)$
windowrule = size 900 600, match:title ^(bluetuith)$
windowrule = center on,    match:title ^(bluetuith)$

# layerrule = noanim, hyprpicker
# layerrule = noanim, selection
