[Icon Theme]
Name=NightElf-Icons
Comment=Folder icons for the NightElf theme. Bundled from Nordic-darker.
Inherits=Zafiro-Nord-Black-Blue,hicolor

# Directory list
Directories=Places/16,Places/22,Places/32,Places/48,apps/scalable

[apps/scalable]
Size=48
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[Places/16]
Context=Places
Size=16
Type=Fixed

[Places/22]
Context=Places
Size=22
Type=Fixed

[Places/32]
Context=Places
Size=32
Type=Fixed

[Places/48]
Size=48
Context=Places
MinSize=32
MaxSize=512
Type=Scalable
