# Basic colors
foreground              #c8d0d8
background              #1c1d24
selection_foreground    #1c1d24
selection_background    #778a9c

# Cursor colors
cursor                  #8ca3b9
cursor_text_color       #1c1d24

# URL underline color
url_color               #778a9c

# Kitty window border colors
active_border_color     #4a8c6a
inactive_border_color   #282c33
bell_border_color       #8c4a52

# OS Window titlebar colors
wayland_titlebar_color  #1c1d24
macos_titlebar_color    #1c1d24

# Tab bar colors
active_tab_foreground   #1c1d24
active_tab_background   #778a9c
inactive_tab_foreground #636d7b
inactive_tab_background #1e2128
tab_bar_background      #1c1d24

# Colors for marks
mark1_foreground #1c1d24
mark1_background #778a9c
mark2_foreground #1c1d24
mark2_background #4a8c6a
mark3_foreground #1c1d24
mark3_background #2f5040

# The 16 terminal colors

# black
color0 #1e2128
color8 #636d7b

# red
color1 #8c4a52
color9 #a65d50

# green
color2 #4a8c6a
color10 #5da87e

# yellow
color3 #a65d50
color11 #c4785e

# blue
color4 #4a6a8c
color12 #778a9c

# magenta
color5 #7a5070
color13 #8699ac

# cyan
color6 #3a7a6a
color14 #8ca3b9

# white
color7 #c8d0d8
color15 #dce1e6
