# Basic colors
foreground              #e6eaeb
background              #1e3144
selection_foreground    #233c53
selection_background    #89A3BC

# Cursor colors
cursor                  #91ADB4
cursor_text_color       #233c53

# URL underline color
url_color               #89A3BC

# Kitty window border colors
active_border_color     #548B84
inactive_border_color   #324458
bell_border_color       #9F6C70

# OS Window titlebar colors
wayland_titlebar_color  #233c53
macos_titlebar_color    #233c53

# Tab bar colors
active_tab_foreground   #233c53
active_tab_background   #89A3BC
inactive_tab_foreground #788A8C
inactive_tab_background #2a3a4e
tab_bar_background      #233c53

# Colors for marks
mark1_foreground #233c53
mark1_background #89A3BC
mark2_foreground #233c53
mark2_background #548B84
mark3_foreground #233c53
mark3_background #175570

# The 16 terminal colors

# black
color0 #2a3a4e
color8 #788A8C

# red
color1 #b95b63
color9 #9a5057

# green
color2 #8ce1a1
color10 #8ccbca

# yellow
color3 #BD7B45
color11 #BD7B45

# blue
color4 #1892c6
color12 #89A3BC

# magenta
color5 #9F6C70
color13 #89A3BC

# cyan
color6 #3fad9e
color14 #91ADB4

# white
color7 #dce1e2
color15 #d1d9db
